[GeneralConfig]
    DelegationLegacyContractAddress = "erd1qqqqqqqqqqqqqpgqxwakt2g7u9atsnr03gqcgmhcv38pt7mkd94q6shuwt"
    LKMEXStakingContractAddress     = "erd1qqqqqqqqqqqqqpgqt7tyyswqvplpcqnhwe20xqrj7q7ap27d2jps7zczse"
    EnergyContractAddress           = "erd1qqqqqqqqqqqqqpgqnyuph46rqr29qv5gqhyxh429zcta8r0ppr9s048rjw"


[AddressPubkeyConverter]
    #Length specifies the length in bytes of an address
    Length = 32
    # Type specifies the type of public keys: hex or bech32
    Type = "bech32"

[Marshalizer]
    Type = "gogo protobuf"

[Cloner]
    [Cloner.ElasticSearchClient]
        Address = "http://127.0.0.1:9200"
        Username = ""
        Password = ""

[Reindexer]
    [Reindexer.SourceElasticSearchClient]
        Address = "http://127.0.0.1:9200"
        Username = ""
        Password = ""


[Destination]
    DestinationElasticSearchClients =  [{ Address = "http://127.0.0.1:9200", Username = "", Password = ""},
                                       { Address = "http://127.0.0.1:9211", Username = "", Password = ""}]

[APIConfig]
    URL = "http://127.0.0.1:7950"
    Username = ""
    Password = ""
